\c postgres;
DROP DATABASE IF EXISTS test WITH (FORCE);
CREATE DATABASE test;

\c test;
DROP USER IF EXISTS dizz;
CREATE USER dizz WITH PASSWORD 'pwd';
GRANT ALL PRIVILEGES ON DATABASE test TO dizz;
GRANT CREATE ON DATABASE test TO dizz;
GRANT ALL ON SCHEMA public TO dizz;